### ISSUE TITLE
How do I use caching in Octokat.js?

### ISSUE THREAD

**Issue by kgrz** [philschatz/octokat.js#92]
Here's the script I've used:

```javascript
  var octo = new Octokat({token: "<token>"});

  var cb = function(result) {
    console.log(result.length);
  };

  var repo = octo.repos("<org>", "<repo>");
  var promise = repo.issues.fetch({status: "open"});

  promise.then(cb);

  setTimeout(function() {
    promise.then(cb);
  }, 10000);
```

The second call to resolve the promise inside the setTimeout does not fetch a new set of issues if I add one on the repo in the 10 seconds time. It logs the same number of issues on both calls. What am I doing wrong?

I'm using the latest library under `dist`.

**Comment by kgrz** [comment]
I have the "log XHR requests" in Chrome turned on, and it seems to register just one XHR request througout. For Etag caching to work it should make another call to the server to check the header, isn't it?

**Comment by philschatz** [comment]
Promises are resolved only once so subsequent calls will return the same value. To get it to work you would need to do something like the following:

```js
  var octo = new Octokat({token: "<token>"});

  var cb = function(result) {
    console.log(result.length);
  };

  var repo = octo.repos("<org>", "<repo>");
  var promise = repo.issues.fetch({status: "open"});

  promise.then(cb);

  setTimeout(function() {
    repo.issues.fetch({status: "open"}).then(cb);
  }, 10000);
```

In case it might be useful, #81 has a way to remember the URL that is constructed and then reuse it later so you do not have to remember the arguments passed into the `.fetch(...)` call. For example:

```js
  var issuesQuery = octo.repos("<org>", "<repo>").issues.params({status: "open"});
  var promise = issuesQuery.fetch();

  promise.then(cb);

  setTimeout(function() {
    issuesQuery.fetch().then(cb);
  }, 10000);
```

Or, if you would prefer to construct/remember the URL yourself:

```js
  var issuesUrl = octo.repos("<org>", "<repo>").issues.params({status: "open"}).url;
  var issuesQuery = octo.fromUrl(issuesUrl);

  // The following is the same as the previous example
  var promise = issuesQuery.fetch();
  promise.then(cb);

  setTimeout(function() {
    issuesQuery.fetch().then(cb);
  }, 10000);
```

**Comment by kgrz** [comment]
I tried the example you provided:

```javascript
  var repo = octo.repos("sinatra", "sinatra");

  repo.issues.fetch({status: "open"}).then(cb);

  setTimeout(function() {
    repo.issues.fetch({status: "open"}).then(cb);
  }, 1000);
```

But I'm still seeing two `200` requests. The second one doesn't seem to be sending the Etag header so that the server can return a `304`
![screenshot 2016-02-03 11 12 07](https://cloud.githubusercontent.com/assets/400299/12774087/7a6823cc-ca67-11e5-8eb2-ff7354368a9d.png)

Is this expected? I can see a speed up in response time between the first and the second calls. First one takes about 1.15s, second one takes about 500ms, so this leads me to believe there's _some_ kind of caching going on—may be the work of the library, or perhaps the caching on Github's side.

**Comment by philschatz** [comment]
So sorry I missed your response! #94 should fix the problem and will be in the next version. Please check if it fixes the issue (it dod for me locally when I tested)

**Comment by kgrz** [comment]
Okay, will check. will reopen this if necessary. Thank you for the help
